---
title: "boostedtree.rmd"
author: "Amy Cook"
date: "August 27, 2015"
output: word_document
---
```{r, echo=FALSE}

library('knitr', lib = 'C:/Progra~1/R/R-3.2.2/library')
library('ggplot2', lib = 'C:/Progra~1/R/R-3.2.2/library')
library("plyr",lib = 'C:/Progra~1/R/R-3.2.2/library')
library("dplyr",lib = 'C:/Progra~1/R/R-3.2.2/library')
library('magrittr',lib='C:/Progra~1/R/R-3.2.2/library')
library('reshape2',lib='C:/Progra~1/R/R-3.2.2/library')
library('caret',lib='C:/Progra~1/R/R-3.2.2/library')
library('randomForest',lib='C:/Progra~1/R/R-3.2.2/library')
library('rpart',lib='C:/Progra~1/R/R-3.2.2/library')
library('rpart.plot',lib='C:/Progra~1/R/R-3.2.2/library')
# library("rpart",lib = 'C:/Program Files/R/R-3.2.2/library')
library('car', lib = 'C:/Progra~1/R/R-3.2.2/library')
library('gbm', lib = 'C:/Progra~1/R/R-3.2.2/library')

# library('e1071', lib = 'C:/Progra~1/R/R-3.2.2/library')
# library('corrgram', lib = 'C:/Progra~1/R/R-3.2.2/library')
# library('party', lib = 'C:/Progra~1/R/R-3.2.2/library')
# library('randomForest', lib = 'C:/Progra~1/R/R-3.2.2/library')
# library('fpc', lib='C:/Progra~1/R/R-3.2.2/library')
# library('vegan', lib = 'C:/Progra~1/R/R-3.2.2/library')
# library(devtools,lib='C:/Progra~1/R/R-3.2.2/library')


library(devtools)
library('knitr')
library('ggplot2')
library("plyr")
library("dplyr")
library('magrittr')
library('reshape2')
library("rpart")
library('car')
library('e1071')
library('corrgram')
library('randomForest')
library('caret')

setwd("C:/Users/n9232371/Documents/Consultbusiness/data")
all7d<- read.csv('~/OneDrive/shared files/Bligh Tanner/masters/data/all7d.csv')[,-1]
all7d$Post.Code<- as.factor(all7d$Post.Code)
```

Create train and test dataframes

```{r, echo=FALSE}
train_ind <- sample(seq_len(nrow(all7d)), size = nrow(all7d)*2/3)

train <- all7d[train_ind, ]
test <- all7d[-train_ind, ]

```



```{r, echo=FALSE}
boost.boston<-gbm(return.pdol ~ inv.mlsto + timespan + no.users + Discipline + pc.pro + 
                     client.totinv + code.director + 
                  Num.disc + Business + Biz.type,
                  data=train, distribution="gaussian",n.trees=5000,
                  shrinkage=0.01,interaction.depth=4,cv.folds=4)
summary(boost.boston)
boost.boston
plot(boost.boston,i="lstat")
plot(boost.boston,i="rm")
```

Not good with lots of levelsssss!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
hm maybe i should encode my whole matrix as a binary dataframe instead of mashing all the forests together!





