---
title: "Financial_Analysis"
author: "Amy Cook"
date: "October 21, 2015"
output: word_document
---

#Assess financial implications for a predictive model

We typically get a confusion matrix built from probabilities


```{r_loadpackages, echo=FALSE, include=FALSE}
library("plyr",lib = 'C:/Progra~1/R/R-3.2.1/library')
library("dplyr",lib = 'C:/Progra~1/R/R-3.2.1/library')
library('magrittr',lib='C:/Progra~1/R/R-3.2.1/library')
library('reshape2',lib='C:/Progra~1/R/R-3.2.1/library')
library('ggplot2',lib='C:/Progra~1/R/R-3.2.1/library')
library('gbm', lib = 'C:/Progra~1/R/R-3.2.2/library')
library('randomForest', lib = 'C:/Progra~1/R/R-3.2.2/library')
library('caret', lib = 'C:/Progra~1/R/R-3.2.2/library')
library('pROC',lib='C:/Progra~1/R/R-3.2.2/library')

# setwd("C:/Users/n9232371/Documents/Consultbusiness/data")
```

Load data 

```{r, echo=FALSE}
test.pred <- read.csv('C:/Users/n9232371/Documents/Consultbusiness/data/test_review.csv')
all7d <- read.csv('C:/Users/n9232371/Documents/Consultbusiness/data/all7d.csv')
test.pred<- merge(test.pred, all7d %>% select(mlsto, balance.mlsto), by = "mlsto")


```


Create vector of profit points

```{r, echo=FALSE}

threshold<- seq(0,1, by=.05)
fin.prof<- rep(0, length(threshold))

for(i in 1:length(threshold)){
        prof<- data.frame("balance" = test.pred$balance.mlsto, 
                  "pred" = test.pred$pred,
                  "ans" = test.pred$b.rpdol)
        #pred = probabilities
        prof$conf <- rep(0, nrow(prof))
        prof$conf <- ifelse(prof$pred >= threshold[i] & prof$ans == 1, 'TP', prof$conf)
        prof$conf <- ifelse(prof$pred >= threshold[i] & prof$ans == 0, 'FP', prof$conf)
        prof$profit<- rep(0, nrow(prof))
        prof$profit<- ifelse(prof$conf %in% "TP", -prof$balance, prof$profit)
        prof$profit<- ifelse(prof$conf %in% "FP", -prof$balance, prof$profit)

        fin.prof[i] = sum(prof$profit)
        
}

prof.plot<- data.frame("threshold" = threshold, "final.profit" = fin.prof)

ggplot(prof.plot, aes(x=threshold, y=final.profit)) + geom_point() + geom_line()

# if say no to all jobs with higher than prob of 0.5, save $500,000

head(prof)

####
# SUMMARY STATS
####

# would dismiss 56 jobs
prof %>% filter(pred>=0.5) %>% nrow

# would dismiss 19 profitable jobs
prof %>% filter(pred >= 0.5 & balance > 0) %>% nrow
#out of 607
prof %>% filter(balance > 0) %>% nrow

# would dismiss 37 losing jobs
prof %>% filter(pred >= 0.5 & balance < 0) %>% nrow
#out of 135
prof %>% filter(balance < 0) %>% nrow

#without algorithm, balance would be $1,475,642
orig.bal<- sum(prof$balance)

# without any losing jobs, balance would be $2,516,246
orig.prof<- prof %>% filter(balance > 0) %>% sum

# without any profitable jobs, balance would be -$1,040,322
orig.loss<- prof %>% filter(balance < 0) %>% sum

#how much real profit would you be dismissing? $82631
prof.dismis<- prof %>% filter(pred >= 0.5 & balance > 0) %>% select(balance) %>% sum
#how much real loss would you be avoiding? $566,481.6
loss.dismis<- prof %>% filter(pred >= 0.5 & balance < 0) %>% select(balance) %>% sum
# total benefit = $483,850
algor.prof<- -(loss.dismis + prof.dismis)

# total balance would be $1,959,492
sum(prof$balance) + algor.prof

# a 32.8% improvement
algor.prof/sum(prof$balance)

```

Write function for making 10 boosted trees and checking the predictions/savings for each!

```{r, echo=FALSE}

all10mice<- read.csv('C:/Users/n9232371/Documents/Consultbusiness/data/all10mice.csv')[,-1]

profit.cv<- function(df.string = "all10mice", method = "boost", seed = 300, k.folds = 3){
        
        results = data.frame('orig.bal' = rep(0, k.folds), 'orig.prof' = rep(0, k.folds), 
                             'orig.loss' = rep(0, k.folds),
                             'prof.dismis' = rep(0, k.folds), 'loss.dismis' = rep(0, k.folds), 
                             'algor.prof' = rep(0, k.folds),
                             'improv' = rep(0, k.folds), 'thresh' = rep(0, k.folds),
                             'auc' = rep(0, k.folds))
        colours <- c("red", "yellow", "green", "blue", "purple")
        
        
        df = get(df.string)
        set.seed(seed)
        
        # create f.rpdol
        df$f.rpdol <- as.factor(df$b.rpdol)
        levels(df$f.rpdol)[levels(df$f.rpdol) == "0"] <-"profit"
        levels(df$f.rpdol)[levels(df$f.rpdol) == "1"] <-"loss"
        
        #set up 10 fold cv using caret function
        folds <- createFolds(df$f.rpdol, k = k.folds, list = T, returnTrain = F)
        #now have folds[[1]] through folds[[10]] list of rows to exclude
        
        
        if(method %in% 'boost') {
                        formula = "b.rpdol ~ Discipline + pc.pro + b.timespan.cbrt + no.users + inv.mlsto.log + client.totinv.log + Business + majority.pos + pc.majpos.log"
        } else {
                formula <-"f.rpdol ~ Discipline + pc.pro + b.timespan.cbrt + no.users + inv.mlsto.log + client.totinv.log + Business + majority.pos + pc.majpos.log + JD.Second + Billing.Type"
        }
        
        
        for (j in 1:length(folds)) {
                        
                        #turn predictors and response into 'ordered' variables for roc() to work
                        test<- df[folds[[j]],]
                        levels(test$f.rpdol) <- c('profit', 'loss')
                        test$f.rpdol <- ordered(test$f.rpdol)
                        
                        
                        if(method %in% 'rf'){
                                fit <- randomForest(as.formula(formula), data = df[-folds[[j]],], 
                                            mtry = 5, ntree = 2000)
                                pred <- predict(fit, test, type = "prob")
                                pred <- pred[,2]
                                
                        } else {
                                if(method %in% 'log'){
                                        fit<- glm(as.formula(formula), 
                                                  data = df[-folds[[j]],], family = binomial())
                                        pred <- predict(fit, test,
                                                        type = "response")
                                } else {
                                        fit <- gbm(as.formula(formula), data = df[-folds[[j]],],
                                                   distribution = "bernoulli", n.trees = 10000,
                                                   shrinkage = 0.001, interaction.depth = 4,
                                                   n.minobsinnode = 20)
                                                
                                                pred <-predict(fit, test, 
                                                               n.tree = 10000, type = "response")
                                                }
                        }
                        
                        #pROC
                        pred.p <- roc(test$f.rpdol, pred)
                        # plot.roc(pred.p, col= colours[i], print.thres=T)
                        
                        results$auc[j] <- auc(pred.p)
                        
                        ##
                        #create full test df
                        test$pred<- pred
                        test.pred <- merge(test, all7d %>% select(mlsto, balance.mlsto), by = "mlsto")
                        
                        
                        #create vector of profit points
                        
                        threshold = seq(0,1, by = .05)
                        fin.prof = rep(0, length(threshold))
                        
                        for (i in 1:length(threshold)) {
                                prof <- data.frame("balance" = test.pred$balance.mlsto,
                                "pred" = test.pred$pred,
                                "ans" = test.pred$b.rpdol)
                                
                                #pred = probabilities
                                prof$conf <- rep(0, nrow(prof))
                                prof$conf <- ifelse(prof$pred >= threshold[i] & prof$ans == 1, 'TP', prof$conf)
                                prof$conf <- ifelse(prof$pred >= threshold[i] & prof$ans == 0, 'FP', prof$conf)
                                prof$profit <- rep(0, nrow(prof))
                                prof$profit <- ifelse(prof$conf %in% "TP",-prof$balance, prof$profit)
                                prof$profit <- ifelse(prof$conf %in% "FP",-prof$balance, prof$profit)
                                
                                fin.prof[i] = sum(prof$profit)
                                
                                }
                        
                        prof.plot<- data.frame("threshold" = threshold, "final.profit" = fin.prof)
                        
                        print(
                        ggplot(prof.plot, aes(x=threshold, y=final.profit)) + geom_point() + geom_line()
                        )
                        
                        best.thresh = arrange(prof.plot, -final.profit)[1,1]
                        results$thresh[j] = best.thresh
                        
                        ####
                        # SUMMARY STATS
                        ####
                        
                        #without algorithm, balance would be $1,475,642
                        results$orig.bal[j] = sum(prof$balance)
                        # without any losing jobs, balance would be $2,516,246
                        results$orig.prof[j] = prof %>% filter(balance > 0) %>% sum
                        # without any profitable jobs, balance would be -$1,040,322
                        results$orig.loss[j] = prof %>% filter(balance < 0) %>% sum
                        #how much real profit would you be dismissing? $82631
                        temp<- prof %>% filter(pred >= best.thresh & balance > 0)
                        results$prof.dismis[j] = ifelse(nrow(temp)>0, temp %>% select(balance) %>% sum,
                                                        0)
                        #how much real loss would you be avoiding? $566,481.6
                        results$loss.dismis[j] = prof %>% filter(pred >= best.thresh & balance < 0) %>% 
                                select(balance) %>% sum
                        
                        #print j value
                        cat(j, " ")
                        
        }
        
        # total benefit = $483,850
        results = transform(results, algor.prof = -(loss.dismis + prof.dismis))
        results = transform(results, improv = algor.prof/orig.bal)
        
        return(results)


}

results.1 <- profit.cv(df.string = "all10mice", method = "log", seed = 400, k.folds = 8)
results.2 <- profit.cv(df.string = "all10mice", method = "boost", seed = 400, k.folds = 8)
results.3 <- profit.cv(df.string = "all10mice", method = "rf", seed = 300, k.folds = 3)


```
